# build server
pnpm --filter @raikou/action-icon run build
pnpm --filter @raikou/alert run build
pnpm --filter @raikou/anchor run build
pnpm --filter @raikou/appshell run build
pnpm --filter @raikou/aspect-ratio run build
pnpm --filter @raikou/background-image run build
pnpm --filter @raikou/badge run build
pnpm --filter @raikou/blockquote run build
pnpm --filter @raikou/breadcrumbs run build
pnpm --filter @raikou/button run build
pnpm --filter @raikou/center run build
pnpm --filter @raikou/close-button run build
pnpm --filter @raikou/code run build
pnpm --filter @raikou/color-swatch run build
pnpm --filter @raikou/container run build
pnpm --filter @raikou/divider run build
pnpm --filter @raikou/fieldset run build
pnpm --filter @raikou/flex run build
pnpm --filter @raikou/grid run build
pnpm --filter @raikou/group run build
pnpm --filter @raikou/highlight run build
pnpm --filter @raikou/kbd run build
pnpm --filter @raikou/loader run build
pnpm --filter @raikou/mark run build
pnpm --filter @raikou/notification run build
pnpm --filter @raikou/paper run build
pnpm --filter @raikou/skeleton run build
pnpm --filter @raikou/stack run build
pnpm --filter @raikou/text run build
pnpm --filter @raikou/title run build
pnpm --filter @raikou/unstyled-button run build
pnpm --filter @raikou/visually-hidden run build