# build client
pnpm --filter @raikou/avatar run build
pnpm --filter @raikou/checkbox run build
pnpm --filter @raikou/color-picker run build
pnpm --filter @raikou/combobox run build
pnpm --filter @raikou/drawer run build
pnpm --filter @raikou/input run build
pnpm --filter @raikou/input-base run build
pnpm --filter @raikou/modal run build
pnpm --filter @raikou/modal-base run build
pnpm --filter @raikou/native-select run build
pnpm --filter @raikou/popover run build
pnpm --filter @raikou/portal run build
pnpm --filter @raikou/scroll-area run build
pnpm --filter @raikou/slider run build
pnpm --filter @raikou/switch run build
pnpm --filter @raikou/tabs run build
pnpm --filter @raikou/table run build
pnpm --filter @raikou/text-input run build
pnpm --filter @raikou/tooltip run build
pnpm --filter @raikou/client run build