[package]
name = "unocss-preset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cssparser = "0.33.0"
regex = "1"
lightningcss = { version = "1.0.0-alpha.50", features = ["visitor", "into_owned"] } 
smallvec = { version = "1.7.0", features = ["union"] }
