[components]
core_dir = [
  "/packages/raikou/server/dist/index.mjs",
  "/packages/raikou/client/dist/index.mjs"
]
other_dir = [
  "@raikou/carousel",
  "@raikou/code-highlight",
  "@raikou/contextmenu",
  "@raikou/datatable",
  "@raikou/dates",
  "@raikou/dial",
  "@raikou/dropzone",
  "@raikou/modals",
  "@raikou/notifications",
  "@raikou/nprogress",
  "@raikou/spotlight",
  "@raikou/tiptap"
]