module.exports = {
  plugins: [
    require("../src/DataTable.plugin"),
    require("../src/DataTableEmptyRow.plugin"),
    require("../src/DataTableEmptyState.plugin"),
    require("../src/DataTableFooter.plugin"),
    require("../src/DataTableFooterCell.plugin"),
    require("../src/DataTableFooterSelectorPlaceholderCell.plugin"),
    require("../src/DataTableHeader.plugin"),
    require("../src/DataTableHeaderCell.plugin"),
    require("../src/DataTableHeaderSelectorCell.plugin"),
    require("../src/DataTableLoader.plugin"),
    require("../src/DataTablePagination.plugin"),
    require("../src/DataTableRow.plugin"),
    require("../src/DataTableRowCell.plugin"),
    require("../src/DataTableRowExpansion.plugin"),
    require("../src/DataTableRowMenu.plugin"),
    require("../src/DataTableRowMenuDivider.plugin"),
    require("../src/DataTableRowMenuItem.plugin"),
    require("../src/DataTableRowSelectorCell.plugin"),
    require("../src/DataTableScrollArea.plugin"),
  ],
};
